export { CommentComponent } from './comment.component';
export { CommentResolver } from './comment.resolver';
export { CommentRouteActivator } from './comment-route-activator.service';
export { CommentsComponent } from './comments.component';
export { CommentsResolver } from './comments.resolver';
export { DetailedCommentComponent } from './detailed-comment.component';
export { DurationPipe } from './shared/duration.pipe';
export { NewCommentComponent } from './shared/new-comment.component';
export { CommentsService } from './shared/comments.service';